language: python
sudo: false
before_script:
  - pip install tox
script:
  - tox
matrix:
  fast_finish: true
  allow_failures:
    - env: TOXENV=docstrings
  include:
    - python: 2.6
      env: TOXENV=py26
    - python: 2.7
      env: TOXENV=py27
    - python: 3.3
      env: TOXENV=py33
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: pypy
      env: TOXENV=pypy
    - env: TOXENV=docstrings
    - env: TOXENV=flake8

notifications:
  irc:
    channels:
      - "irc.freenode.org##python-code-quality"
    use_notice: true
    skip_join: true
